# Fase de construcción para el backend
[phases.backend]
command = "cd backend && npm install && npm run build"

# Fase de construcción para el frontend
[phases.frontend]
command = "cd frontend && npm install && npm run build"

# Fase de inicio para la aplicación
[phases.start]
command = "cd backend && npm run start"
